import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function generatePDF(result) {
  const doc = new jsPDF();

  // ---------- HEADER ----------
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("AI Resume Analyzer", 20, 20);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    20,
    30
  );

  // ---------- SCORE TABLE ----------
  autoTable(doc, {
    startY: 40,
    head: [["Metric", "Score"]],
    body: [
      ["Keyword Score", `${result.keyword_score}%`],
      ["Semantic Score", `${result.semantic_score}%`],
      ["Final AI Score", `${result.final_ai_score}%`],
    ],
    theme: "grid",
    headStyles: {
      fillColor: [37, 99, 235],
    },
  });

  let y = doc.lastAutoTable.finalY + 15;

  // ---------- Resume Skills ----------
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Resume Skills", 20, y);

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.text(result.resume_skills.join(", "), 20, y, {
    maxWidth: 170,
  });

  y += 25;

  // ---------- Matched ----------
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Matched Skills", 20, y);

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.text(result.matched_skills.join(", "), 20, y, {
    maxWidth: 170,
  });

  y += 25;

  // ---------- Missing ----------
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Missing Skills", 20, y);

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.text(result.missing_skills.join(", "), 20, y, {
    maxWidth: 170,
  });

  // ---------- AI REVIEW ----------
  doc.addPage();

  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("AI Resume Review", 20, 20);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const review = doc.splitTextToSize(
    result.ai_review,
    170
  );

  doc.text(review, 20, 35);

  // ---------- Suggestions ----------
  let suggestionY = 180;

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Suggestions", 20, suggestionY);

  suggestionY += 10;

  doc.setFont("helvetica", "normal");

  result.suggestions.forEach((item) => {
    const lines = doc.splitTextToSize(
      "• " + item,
      170
    );

    doc.text(lines, 20, suggestionY);

    suggestionY += lines.length * 7 + 4;
  });

  // ---------- Footer ----------
  const pageCount = doc.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);

    doc.setFontSize(10);

    doc.text(
      `Generated by AI Resume Analyzer | Page ${i} of ${pageCount}`,
      20,
      290
    );
  }

  doc.save("AI_Resume_Report.pdf");
}